#!/bin/bash
#SBATCH --nodes=1
#SBATCH --time=23:59:59
#SBATCH --mem=40gb

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #### 
#### Script for filtering and annotating the imputed (Minimac) VCF files

if [[ -z "$1" ]]
then
    echo "Error: No cohort name"
    exit
fi

if [[ -z "$2" ]]
then
    echo "Error: no chr"
    exit
fi

if [[ -z "$3" ]]
then
    echo "Error: no input"
    exit
fi

if [[ -z "$4" ]]
then
    echo "Error: no output directory selected"
    exit
fi

if [[ -z "$5" ]]
then
    echo "Error: no ref panel for the rsID annotation"
    exit
fi

echo "cohort: ${1}"
cohort=$1
#cohort="Foresters"
echo "chr: ${2}"
chr=$2
#chr=22
echo "input: ${3}"
inputVCF=$3
#inputVCF="/groups/umcg-wijmenga/tmp04/umcg-vmatzaraki/imputedData/imputed_ForestersFull/chr_22/chr22.dose.vcf.gz"
inputDir="$(dirname "${inputVCF}")/"
echo "outputDir ${4}" 
outputDir=$4
#outputDir="/groups/umcg-wijmenga/tmp04/umcg-vmatzaraki/imputedData/imputed_ForestersFull/Foresters_post/"

echo "reference Panel (for rsID annotation): ${5}"
snpDB=$5
#snpDB="/groups/umcg-wijmenga/tmp04/umcg-raguirre/human_9606_b147_GRCh37p13_SNPdb.vcf.gz"

##### modules 
module load BCFtools/1.3-foss-2015b 
module load tabix
module load VCFtools
module load R

#### Filtering and annotation of michigan imputed VCF files. 

################################################
#### #### Add proper header for BCFtools to work with

#### write the header to then modify it in with michiganReheading.R

midOut="${outputDir}/header/chr_${chr}/"
mkdir -p $midOut

bcftools view -h \
$inputVCF \
> "${midOut}hdr.txt"

cd $midOut
Rscript /groups/umcg-weersma/tmp04/Michiel/GSA-redo/imputation/annotation/michiganReheading.R "${midOut}hdr.txt"

midOut="${outputDir}/header/chr_${chr}/"
mkdir -p $midOut

vcfNewHeader="chr_${chr}_header.vcf.gz"
bcftools reheader \
--header "${midOut}hdr_michigan.txt" \
--output "${midOut}${vcfNewHeader}" \
$inputVCF

tabix "${midOut}${vcfNewHeader}"

################################################
#### Filtering
#### #### MAF >= 0.1
#### #### R2 >= 0.3
#### #### ER2 >= 0.3
filterOut="${outputDir}/filtered/chr_${chr}/"
mkdir -p $filterOut

vcfFiltered="chr_${chr}_filtered.vcf.gz"
bcftools view -i 'MAF[0]>=0.01 & (R2[0]>=0.3 || ER2[0]>=0.3)' \
--output-file "${filterOut}${vcfFiltered}" \
--output-type z \
"${midOut}${vcfNewHeader}"

tabix "${filterOut}${vcfFiltered}"

################################################
#### Annotation of snpDB identifier (rs number)
################################################

################################################
#### #### remove identifiers
vcfFilteredNoID="chr_${chr}_noID.vcf.gz"

noIDout="${outputDir}/noID/chr_${chr}/"
mkdir -p $noIDout

bcftools annotate \
--output "${noIDout}${vcfFilteredNoID}" \
--output-type z \
--remove ID \
"${filterOut}${vcfFiltered}"

tabix "${noIDout}${vcfFilteredNoID}"

################################################
#### #### annotate 
annotatedOut="${outputDir}/annotated/chr_${chr}/"
mkdir -p $annotatedOut

vcfAnnotated="chr_${chr}_annotated.vcf.gz"
bcftools annotate \
--annotations $snpDB \
--columns ID \
--output "${annotatedOut}${vcfAnnotated}" \
--output-type z \
"${noIDout}${vcfFilteredNoID}"

tabix "${annotatedOut}/${vcfAnnotated}"
